apiVersion: apps/v1
kind: Deployment
metadata:
  name: config
  labels:
    app: config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config
  template:
    metadata:
      labels:
        app: config
    spec:
      containers:
      - name: config-service
        image: mehike/config-service:0.0.1
        ports:
        - containerPort: 8088
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: postgresdb
              key: database-name
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgresdb
              key: database-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresdb
              key: database-password
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: postgresdb
              key: database-host
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: postgresdb
              key: database-port

