apiVersion: v1
kind: Service
metadata:
  name: eureka
  labels:
    app: eureka
spec:
  externalIPs:
  - 192.168.1.156
  - 88.196.63.92
  ports:
  - port: 8061
    protocol: TCP
    targetPort: 8061
  selector:
    app: eureka
  type: NodePort
