apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
  labels:
    app: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - name: eureka-discovery
        image: mehike/eureka-discovery:0.0.1
        ports:
        - containerPort: 8061
        env:
        - name: CONFIG_SERVICE
          valueFrom:
            configMapKeyRef:
              name: config
              key: service-prt
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgresdb
              key: database-user

